notifications:
  on_success: never
  on_failure: never

language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.6'
      - COMPLETE=false
      - BIN=true
      - SRC=true
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.7.3'
      - COMPLETE=false
      - BIN=true
      - SRC=false
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.8'
      - COMPLETE=true
      - BIN=true
      - SRC=false
  - os: osx
    env:
      - PY_VERSION='3.6'
      - COMPLETE=false
      - BIN=true
      - SRC=false
  - os: osx
    env:
      - PY_VERSION='3.7'
      - COMPLETE=false
      - BIN=true
      - SRC=false
  - os: osx
    env:
      - PY_VERSION='3.8'
      - COMPLETE=false
      - BIN=true
      - SRC=false

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then MINICONDA=Miniconda3-latest-Linux-x86_64.sh;  fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh; fi
  - wget https://repo.continuum.io/miniconda/$MINICONDA
  
  - bash $MINICONDA -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - if [ $COMPLETE == true ];  then conda env create -q -f environment.yml; fi
  - if [ $COMPLETE == true ];  then conda install -n biotite-dev python=$PY_VERSION; fi
  - if [ $COMPLETE == false ]; then conda create -q -n biotite-dev python=$PY_VERSION; fi
  - if [ $COMPLETE == false ]; then conda install -n biotite-dev "cython>=0.29" "numpy>=1.13" "requests>=2.12" "msgpack-python>=0.5.6" "pytest>=3.2"; fi
  - source activate biotite-dev

script:
  - if [ $COMPLETE == true ];  then python setup.py test --pytest-args="--ignore=tests/application/test_blast.py"; fi
  - if [ $COMPLETE == false ]; then python setup.py test --pytest-args="--ignore=tests/structure/test_trajectory.py --ignore=tests/application/ --ignore=tests/database/ --ignore=tests/test_doctest.py"; fi

before_deploy:
  - if [ $SRC == true ]; then python setup.py sdist; fi
  - if [ $BIN == true ]; then python setup.py bdist_wheel; fi
  - if [ $BIN == true ] && [ $TRAVIS_OS_NAME == "linux" ]; then rename 's/linux/manylinux1/g' dist/*.whl; fi
  - if [ $COMPLETE == true ]; then python setup.py build_sphinx; fi
  - if [ $COMPLETE == true ]; then cd doc/_build; fi
  - if [ $COMPLETE == true ]; then mv html doc; fi
  - if [ $COMPLETE == true ]; then zip -r doc.zip doc; fi
  - if [ $COMPLETE == true ]; then cd ../..; fi

deploy:
  provider: releases
  api-key:
    secure: ncH32tO1V1vJMgpHY/JJ+TDpFkj0uFzNVeD2tBFq+uCDSRzQo8hiC+kFveciQNr9UuKFyqBySFpjP+g93f9xWcjruzTbT42vhoM6YzddMcQI/yiINWoco1Lk8RZpv6HsWeLXPFzP6BWWwBH+1rF09AXX4hk5nHGOlawM+f1nwCoqZrvPc5mhfN/JytRgUjjVZ1yI9VL77wMakGYsuuBpgjpk1AC5bG2X0aCYSRub7kAl3CYPvrknx38pbtL8d9mMyFwLe1UVxuyhY5PZ1hzk+6Dkjwx0mWQ95TCoTOwPU2ECF81gORVd/HZeQ/xRPYb8mlufy+v7pjUgMRQVMwjRR+e3JYHxoAjbN41WUYZohyIeVGnQ9hlaa59EHoDyGL6hJFqJ2o7E5DoKCGE+ssQ/pAmczPMCf3lG4nhgA80WXo9fcchMqPqB1uX43gv+qWvLy3N8V+pzK9nQpUsjKXKROp5fABIaz56APUaq1UrzaAvPHUlNiixjWd7FCU9nDGig8vGSfGNumBUFOQHnS12eQ0ICzTK7z9SuigkEAkB236AiopD5d0fZyyz9hWvWua22wqBD4kwtIQczFos5JHibv1taWdtnxs+/XAJpcV6EWYdTpNEItejRjtPRv20Ddx+G3176aYKbXWrANk/F4sp/HgGaLR7xUiH1wabd6QS5OUE=
  file:
    - dist/*
    - doc/_build/doc.zip
  file_glob: true
  on:
    repo: biotite-dev/biotite
    tags: true
  skip_cleanup: true
