name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test-simple:
    name: Testing
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            python: '3.7'
            numpy: '1.15'
          - os: ubuntu-18.04
            python: '3.8'
            numpy: '1.16'
          - os: ubuntu-18.04
            python: '3.9'
            numpy: '1.19'
          - os: macos-latest
            python: '3.7'
            numpy: '1.15'
          - os: macos-latest
            python: '3.8'
            numpy: '1.16'
          - os: macos-latest
            python: '3.9'
            numpy: '1.19'
          - os: windows-latest
            python: '3.7'
            numpy: '1.15'
          - os: windows-latest
            python: '3.8'
            numpy: '1.16'
          - os: windows-latest
            python: '3.9'
            numpy: '1.19'

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: fastpdb-test
          auto-update-conda: true
          python-version: ${{ matrix.python }}
      - name: Installing dependencies
        run: conda install -c conda-forge numpy=$NUMPY_VERSION "biotite>=0.29" maturin pytest
        env:
          NUMPY_VERSION: ${{ matrix.numpy }}
      - name: Building distribution
        run: maturin build --release -o dist
      - name: Installing distribution
        run: pip install .//dist//*.whl
      - name: Testing code
        run: pytest
